# Generated by Django 4.0.5 on 2022-12-21 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
