# Generated by Django 4.0.5 on 2022-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0002_subscriber_subscribercategory_subscriber_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
