# Generated by Django 4.0.5 on 2022-12-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0002_commentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs_work.commentstatus'),
        ),
    ]
