# Generated by Django 4.0.5 on 2022-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0004_commentcommentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
