# Generated by Django 4.0.5 on 2022-12-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0005_commenttone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tone',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='docs_work.commenttone'),
        ),
    ]
