# Generated by Django 4.0.5 on 2022-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0006_comment_tone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentCommentStatus',
        ),
    ]
