# Generated by Django 4.0.5 on 2022-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0007_delete_commentcommentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='adopted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rejected',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
