# Generated by Django 4.0.5 on 2022-12-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0009_comment_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='received',
        ),
    ]
