# Generated by Django 4.0.5 on 2022-12-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0010_remove_comment_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='received',
            field=models.BooleanField(null=True),
        ),
    ]
